### ISSUE TITLE
User Story: Navigation

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#11]
As a **site user**, I can **quickly and intuitively view the navigation bar**, in order to **easily navigate through the site.**.

---
### Acceptance Criteria

1. The navigation bar is available and legible on all devices
2. The navigation bar displays the current page
3. The navigation bar appears on every page

---
### Tasks

- [x] Add bootstrap scripts
- [x] Create base.html template
- [x] Set up settings, URL and view to render template
- [x] Add navigation element
- [x] Create templates for all necessary pages
