### ISSUE TITLE
User Story: Progress Long Term Goal

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#14]
As a **student**, I can **update the progress of my long-term goal**, in order to **record my development**.

---
### Acceptance Criteria

1. Student can update the progress of a goal
2. Current progress is displayed on the Dashboard

---
### Tasks

- [x] Show/Hide Range Inputs for each goal
- [x] Add form, URL and view for updating goal 
- [x] Wire up form on submission
