### ISSUE TITLE
User Story: Create Practice Session Entry

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#15]
As a **student**, I can **create a record of an individual practice session**, in order to **record my work towards my goals**.

---
### Acceptance Criteria

1. Information (including date, duration and focus areas) can be captured via a form.
2. Information is reliably stored in the database.
3. Information is validated.
4. User is redirected to the Dashboard after successful submission.
5. User is alerted to errors if unsuccessful.

---
### Tasks

- [x] Create Session Model
- [x] Create New Sesion Form
- [x] Render Form
- [x] Write Post Method
- [x] Redirect after successful submission
