### ISSUE TITLE
User Story: Delete Practice Sessions

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#16]
As a **student**, I can **remove a practice session entry**, in order to **remove unintentional entries.**.

---
### Acceptance Criteria

1. A session can be removed from the journal using a button
2. Defensive programming is employed to prevent unwanted removal

---
### Tasks

- [x] Add Delete Practice Button
- [x] Create Modal for Defensive Programming
- [x] Add url and view method to handle Delete Practice
