### ISSUE TITLE
User Story: Save Articles

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#25]
As a **student**, I can **''favourite'' articles**, in order to **gather the most relevant resources for revision and sharing**.

---
### Acceptance Criteria

1. User can mark an article as a favourite
2. A link to favourite articles appears on the user's dashboard

---
### Tasks

- [x] Create 'Favourite Button' for authenticated users
- [x] Create URL and View to handle adding Resource as Favourite
- [x] Render Favourite Resources on Dashboard
