### ISSUE TITLE
User Story: Add Long Term Goals

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#3]
As a **student**, I can **create and monitor a long-term goal**, in order to **track my progress towards a specific target**.

---
### Acceptance Criteria

1. Students can add a long-term goal
2. Goal is viewable on Dashboard
3. Progress towards the goal is reflected on the Dashboard

---
### Tasks

- [x] Create Form to Allow User Input
- [x] Add method to view
- [x] Display progress bar next to label on dashboard
- [x] Style Form

**Comment by denham-ed** [comment]
Resolved by #37
