### ISSUE TITLE
User Story: Practice Calendar

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#4]
As a **student**, I can **view a calendar that displays my past practice days**, in order to **view my successful habit-building**.

---
### Acceptance Criteria

1. A calendar-like widget appears on the dashboard
2. Days, when practice has been recorded, are identified
3. User can see the dates attached to each session.

---
### Tasks

- [x] Render 30 divs to indicate days
- [x] Create list of dictionaries with dates and practiced status for 30 days.
- [x] Conditionally style divs to reflect practiced status
- [x] Add tooltips to show dates
