### ISSUE TITLE
User Story: Dashboard Report

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#5]
As a **student**, I can **review my practice totals**, in order to **build momentum and review my progress**.

---
### Acceptance Criteria

1. Data (eg days practised in a row, total duration of practice, key areas of focus) are displayed to the user

---
### Tasks

- [x] Aggregate total practice minutes of all sessions, last 7 days and last 30 days
- [x] Aggregate and display Focus as a chart
- [x] Aggregate and display Moods as a wordcloud
