### ISSUE TITLE
User Story: Footer

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#6]
As a **site user**, I can **always see a website footer**, in order to **learn key information about the site**.

---
### Acceptance Criteria

1. Footer must appear on every page
2. Footer contains brand and tagline
3. Footer contains links to GitHub and LinkedIn
4. Links should open in new tab

---
### Tasks

- [x] Create a footer outline
- [x] Attach the footer to the bottom of page
- [x] Add 'social' links
