### ISSUE TITLE
User Story: Sign-Up

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#7]
As a **site user**, I can **register**, in order to **access the controlled areas of the site**.

---
### Acceptance Criteria

1. Users can register using a unique username and password
2. Sign up should also gather first and last names and an email address
3. A role should be created that includes fields for 'goals' and 'resources'

---
### Tasks

- [x] Extend User model
- [x] Create a sign-up form
- [x] Add validation to form
- [x] Add a link to the navigation bar
- [x] Style sign-up page
