### ISSUE TITLE
User Story: Sign In

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala_v2#8]
As a **site user**, I can **sign in to my account**, in order to **access my practice records**.

---
### Acceptance Criteria

1. Users can sign in quickly using the username and password that they registered with
2. Users are alerted when something isn't working
3.  After signing in, users are taken to the dashboard

---
### Tasks

- [x] Create sign-in form
- [x] Style sign-in form
- [x] Display error messages
